baseURL = 'https://0xmang.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Project'
theme = 'hugo-theme-terminalcv'

[params]
  author = "Rabih"
  description = "Security learning, CTF walkthroughs, and how-to's"

[[menu.main]]
  identifier = "about"
  name = "About"
  pageRef = "/about"
  weight = 1

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  pageRef = "/resume"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  pageRef = "/blogs"
  weight = 3

[[menu.main]]
  identifier = "post"
  name = "Posts"
  pageRef = "/posts"
  weight = 3
